### ISSUE TITLE
hey you forgot to add the database clinic.sql 

### ISSUE THREAD

**Issue by oumelkheirboudali** [viral98/ClinicApplication#1]
can u plz upload the clinic database and exported from phpmyadmin plz ? i really need it and if u may plz sent it to me in my email 
oumelkheir-1993@hotmail.com
or 
oumelkheir1993@gmail.com
 plz i really need it ^^" and thank you for ur hard work .

**Comment by viral98** [comment]
Hey! I actually did I fresh install of windows and in that I forgot to take a backup of the sql files
Sorry for the Inconvenience !
